allure-framework/allure-js

Jenkinsfile
package.json
packages/allure-cucumberjs/package.json
packages/allure-jasmine/package.json
packages/allure-mochajs/package.json

Separated build from test; Added Jenkinsfile

---

Jenkinsfile
lerna.json
package.json

[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

Releasing process

---

Jenkinsfile

[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

Some fixes to npm publish

---

Jenkinsfile

[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

Fix release stage

---

.github/PULL_REQUEST_TEMPLATE.md
LICENSE.txt
README.md
packages/allure-cucumberjs/LICENSE.txt
packages/allure-jasmine/LICENSE.txt
packages/allure-jest/LICENSE.txt
packages/allure-js-commons/LICENSE.txt
packages/allure-mochajs/LICENSE.txt

[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

Repo clean up

---

packages/allure-jasmine/package.json
packages/allure-jasmine/src/JasmineAllureReporter.ts
packages/allure-jasmine/test/label.test.ts
packages/allure-jasmine/test/setup.ts

add test for labels

---

Jenkinsfile
packages/allure-mocha/package.json
packages/allure-mocha/test/mocha.opts
packages/allure-mocha/test/runner.ts

Let's see if this works.
UPD: worked! https://ci.qameta.io/job/allure-js/job/PR-41/2/allure/#suites/4ac524fac60485f69e27bd1fd26989f7/6d62a16bc8ef4405/

render demo report for mocha tests

---

.eslintrc.yml
packages/allure-cucumberjs/features/.eslintrc.yml
packages/allure-cucumberjs/features/step_definitions/report.steps.ts
packages/allure-cucumberjs/features/support/report.ts
packages/allure-cucumberjs/features/support/world.ts
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/src/utilities.ts
packages/allure-jasmine/test/matchers.ts
packages/allure-jasmine/test/status.test.ts

Fix errors and warnings

---

packages/allure-jasmine/test/helpers.ts
packages/allure-jasmine/test/label.test.ts
packages/allure-jasmine/test/setup.ts
packages/allure-jasmine/test/status.test.ts
packages/allure-jasmine/test/step.test.ts

Rft jasmine tests

---

.github/workflows/release.yml
package.json

Lerna release from git

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts

Fullname cucmberjs

---

.github/workflows/release.yml

Fetch all tags for lerna

---

.github/workflows/release.yml

Up checkout version

---

package.json

Do not tagging package.json update

---

.github/workflows/release.yml

deatached head workaround

---

package.json

do not commit version

---

.github/workflows/release.yml
package.json

do not use checkout action

---

.github/workflows/release.yml

Reattach head via checkout ref

---

.github/workflows/release.yml

Next try to fix lerna in gh action

---

.github/workflows/release.yml

Reattach head

---

lerna.json
packages/allure-cucumberjs/package.json
packages/allure-jasmine/package.json
packages/allure-jest/package.json
packages/allure-js-commons/package.json
packages/allure-mocha/package.json

Bump v2.0.0-beta.7

---

lerna.json
packages/allure-cucumberjs/package.json
packages/allure-jasmine/package.json
packages/allure-jest/package.json
packages/allure-js-commons/package.json
packages/allure-mocha/package.json

Bump version up to beta.9

---

.github/workflows/release.yml

Create new version

---

packages/allure-js-commons/index.ts
packages/allure-js-commons/package.json
packages/allure-js-commons/src/AllureRuntime.ts
packages/allure-js-commons/src/writers/AllureWriter.ts
packages/allure-js-commons/src/writers/FileSystemAllureWriter.ts
packages/allure-js-commons/src/writers/InMemoryAllureWriter.ts
packages/allure-js-commons/test/runner.ts
packages/allure-js-commons/test/specs/FileSystemAllureWriter.spec.ts
packages/allure-js-commons/test/tsconfig.json
yarn.lock

Fix attachments from path

---

packages/allure-mocha/src/AllureReporter.ts
packages/allure-mocha/src/MochaAllureReporter.ts
packages/allure-mocha/test/fixtures/specs/hooks.ts
packages/allure-mocha/test/specs/hooks.ts

Add mocha hook names

---

packages/allure-playwright/src/helpers.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/status-details.spec.ts

``` js
allure.description("description");
```
update for https://github.com/allure-framework/allure-js/pull/408#issuecomment-979772959

Playwright - Add description attribute

---

packages/allure-playwright/README.md
packages/allure-playwright/src/index.ts

Fixes https://github.com/allure-framework/allure-js/issues/405

feat(playwright): add custom outputFolder in config

---

packages/allure-playwright/package.json
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/labels.spec.ts
yarn.lock

The original implementation
- Generates Allure tests results data only when test is finished.
- Has some invalid methods (e.g. `onTimeout`).
This PR upgrades Playwright Test to latest version to reflect latest Playwright API. All tests are passing.

Generate Allure results in real-time

---

packages/allure-playwright/package.json
packages/allure-playwright/test/fixtures.ts
packages/allure-playwright/test/label.spec.ts
packages/allure-playwright/test/labels.spec.ts
packages/allure-playwright/test/link.spec.ts
packages/allure-playwright/test/status.spec.ts
packages/allure-playwright/test/stdio.spec.ts
packages/allure-playwright/test/steps.spec.ts
yarn.lock

It was yelling inside VSCode a lot because of these eslint warnings.

test(playwright): fix ts-ignore and eslint warnings

---

packages/allure-playwright/README.md

Adding several sections and reordering the existing inside the file README.md inside the package: allure-js\packages\allure-playwright

chore(playwright) Readme improvements

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts

Makes the reporter able to work in cucumber parallel mode.
fixes #455

fix parallel mode

---

packages/allure-cucumberjs/README.md
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts

Provide the same API for labels as for links (#458)

improvement(cucumberjs): update custom labels api

---

packages/allure-mocha/.eslintrc.js
packages/allure-mocha/README.md
packages/allure-mocha/runtime.d.ts
packages/allure-mocha/runtime.js
packages/allure-mocha/src/AllureReporter.ts
packages/allure-mocha/src/MochaAllureReporter.ts
packages/allure-mocha/test/runner.ts
packages/allure-mocha/test/tsconfig.json

fixes #245
Fixes parallel mode for allure mocha report

Base fix for mocha parallel mode

---

packages/allure-js-commons/index.ts
packages/allure-js-commons/src/Allure.ts
packages/allure-js-commons/src/ExecutableItemWrapper.ts
packages/allure-js-commons/src/model.ts
packages/allure-playwright/src/helpers.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/parameters.spec.ts

Add parameters to allure-playwright

---

packages/allure-js-commons/src/model.ts
packages/allure-js-commons/src/writers/utils.ts

This PR fixes the runtime exception reported in https://github.com/allure-framework/allure-js/issues/487

Support content-type 'text/html' for attachments

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts
packages/allure-js-commons/src/AllureTest.ts

fixes #518
Full Name allow result to have historical data and create testcases in testops

feat(cucumber): add fullName and testCaseId props

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/history.spec.ts

fix(playwright): fix historyId field

---

packages/allure-cucumberjs/package.json
yarn.lock

remove unused dependencies so dependabot stop spamming

chore(cucumberjs): cleanup deps

---

packages/allure-js-commons/src/model.ts
packages/allure-playwright/src/helpers.ts

feature(playwright): add layer helper

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/stdio.spec.ts

fix(playwright): fix multiple stout and stderr

---

packages/allure-cucumberjs/README.md
packages/allure-mocha/README.md
packages/allure-playwright/README.md

chore(docs): Add parameter examples and docs to readme

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/stdio.spec.ts

fix(playwright): Strip ansii colors from stdout and stderr

---

packages/allure-playwright/package.json
packages/allure-playwright/src/index.ts
yarn.lock

fix(playwright): fix timeline threads for playwright

---

packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/tests/errorMessage.test.ts

fix(newman): Fix messages escape

---

packages/allure-jasmine/src/JasmineAllureReporter.ts
packages/allure-jasmine/test/simple-fixtures.test.ts

fix https://github.com/allure-framework/allure-js/issues/558

fix(jasmine): fix global afterAll, beforeAll usages and support `@testing-library/react`

---

packages/newman-reporter-allure/src/index.ts

fix(newman): Fix critical newman description bug

---

packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/tests/overview.test.ts

fix(newman): fix step duration for passed steps

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/global-fail.spec.ts
packages/allure-playwright/test/skip.test.ts

fix(playwright): report skipped results on global fail

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/with_labels_test.ts

fixes #616 
Adds support for feature level custom labels and links.

Fix cucumber labels patterns for features

---

packages/allure-codeceptjs/src/index.ts

Creating a new test...
----------------------
? Feature which is being tested (ex: account, login, etc) rrrr ? Filename of a test rrrr_test.js
Could not load plugin allure from module 'allure-codeceptjs': Cannot destructure property 'event' of 'global.codeceptjs' as it is undefined. TypeError: Cannot destructure property 'event' of 'global.codeceptjs' as it is undefined.
at Object.<anonymous> (/home/mmajorov/ttest/node_modules/allure-codeceptjs/dist/index.js:7:9)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at …

fix(codeceptjs): fix codeceptjs import

---

packages/allure-codeceptjs/README.md

fix: improve readme for easy copy/paste

docs(codeceptjs): improve readme for easy copy/paste

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/undefined_step_defs_test.ts

Handle cucumber tests without implementation

---

packages/allure-codeceptjs/README.md
packages/allure-js-commons/src/model.ts
packages/allure-js-commons/src/writers/utils.ts

Just like in #487 the content type for video/mp4 is missing.
I had the same problem but instead I'm using Mocha via WDIO adding MP4 files generated by Puppeteer-Screen-Recorder

Add support for content type video/mp4

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/exception_formatter_test.ts

Fix cucumberjs exception formatter

---

packages/allure-js-commons/package.json
packages/allure-js-commons/src/utils.ts
packages/allure-js-commons/test/specs/utils.spec.ts
yarn.lock

Add util to classify test errors

---

packages/allure-hermione/src/index.ts

add correct test id generation for hermione reporter

---

.github/workflows/build.yml
packages/allure-hermione/test/.hermione.conf.js
packages/allure-hermione/test/runner.ts

Cache hermione browsers

---

packages/allure-playwright/package.json
packages/allure-playwright/src/index.ts
packages/allure-playwright/src/testplan.ts
packages/allure-playwright/test/fixtures.ts
packages/allure-playwright/test/global-fail.spec.ts
packages/allure-playwright/test/steps.spec.ts
yarn.lock

Bump @playwright/test from 1.30.0 to 1.34.1

---

.github/workflows/build.yml
.github/workflows/lint.yml

It would be better to split test and lint job because sometimes it's difficult to understand which one has been failed, or one failed job can cancel another one and we need to repeat them many times after any fix.

Run lint job separately

---

packages/allure-hermione/test/fixtures/hooks.js
packages/allure-hermione/test/spec/hooks.test.ts

fixes #644
The PR provides only unit tests as a proof for the requested functionality

Add test for hermione browser commands inside hooks

---

packages/allure-hermione/src/index.ts

allure-hermione: do not throw errors when session hasn't been started

---

packages/allure-hermione/docs/development.md
packages/allure-hermione/package.json
packages/allure-hermione/src/index.ts
packages/allure-hermione/test/.hermione.conf.js
packages/allure-hermione/test/fixtures/attachments.js
packages/allure-hermione/test/fixtures/hooks.js
packages/allure-hermione/test/fixtures/labels.js
packages/allure-hermione/test/fixtures/links.js
packages/allure-hermione/test/fixtures/parameters.js
packages/allure-hermione/test/fixtures/steps.js
yarn.lock

Make hermione reporter compatible with hermione@7

---

packages/allure-cucumberjs/package.json
packages/allure-cucumberjs/test/runner.ts
packages/allure-cucumberjs/test/specs/step_arguments_test.ts
packages/allure-cucumberjs/test/specs/with_labels_test.ts
yarn.lock

fixes #755 
The PR doesn't actually change current reporter behavior it just adds a test, to show, that the expected functionality already has been implemented

Add test as proof of feature wide cucumber labels

---

packages/allure-js-commons/index.ts
packages/allure-js-commons/src/utils.ts
packages/allure-playwright/README.md
packages/allure-playwright/src/index.ts
packages/allure-playwright/src/utils.ts
packages/allure-playwright/test/testplan.spec.ts
packages/allure-playwright/test/title-metadata.spec.ts

fix(playwright): Delete metadata from test name

---

.github/workflows/build.yml
packages/allure-hermione/package.json
yarn.lock

Update hermione dependencies to make tests pass

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/attachment-steps.spec.ts
packages/allure-playwright/test/reporter-options.spec.ts
packages/allure-playwright/test/steps.spec.ts

Make Playwright detail and suiteTitle options true by default (fixes #710)

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/label-override.spec.ts

impr(playwright): allow default suite labels override

---

packages/allure-playwright/src/helpers.ts

fixes https://github.com/allure-framework/allure-js/issues/775

fix(playwright): fix missed uuid dep

---

packages/allure-js-commons/index.ts
packages/allure-js-commons/src/testplan.ts
packages/allure-playwright/src/testplan.ts
packages/allure-playwright/test/attachment.spec.ts
packages/allure-playwright/test/environmentInfo.spec.ts
packages/allure-playwright/test/fixtures.ts
packages/allure-playwright/test/label-override.spec.ts
packages/allure-playwright/test/testplan.spec.ts

Minor refactoring of pw tests

---

.pnp.cjs
packages/allure-js-commons/package.json
packages/allure-js-commons/src/AllureGroup.ts
packages/allure-js-commons/src/AllureTest.ts
packages/allure-js-commons/test/specs/AllureTest.spec.ts
yarn.lock

Fix Allure global labels from env variables

---

packages/allure-jest/src/AllureJest.ts

Fixes problem with jest reporter configuration

Fix Allure Jest configuration

---

packages/allure-jest/src/AllureJest.ts
packages/allure-jest/src/utils.ts
packages/allure-jest/test/fixtures/ansiColors.test.js
packages/allure-jest/test/spec/ansiColors.test.ts

fix https://github.com/orgs/allure-framework/discussions/2176

Remove ANSI color codes from jest test results

---

packages/allure-hermione/src/index.ts

Change hermione skipped tests logic

---

packages/allure-jest/README.md
packages/allure-jest/src/AllureJest.ts
packages/allure-jest/src/AllureJestApi.ts
packages/allure-jest/test/fixtures/links.test.js
packages/allure-jest/test/jest.config.js
packages/allure-jest/test/spec/links.test.ts
packages/allure-js-commons/index.ts

Enchance jest runtime links

---

packages/allure-playwright/README.md

Fix playwright readme typo

---

packages/allure-playwright/test/hooks.spec.ts

Add tests for playwright hooks

---

packages/allure-codeceptjs/package.json
packages/allure-cucumberjs/package.json
packages/allure-decorators/package.json
packages/allure-hermione/package.json
packages/allure-jasmine/package.json
packages/allure-jest/package.json
packages/allure-js-commons/package.json
packages/allure-mocha/package.json
packages/allure-playwright/package.json
packages/newman-reporter-allure/package.json

Add homepages for npm

---

packages/allure-vitest/test/utils.ts

Remove deprecated rmdir function usage

---

README.md

Merge the PR, when the package will appear in the npm registry

Add vitest entry point to the root readme file

---

packages/allure-hermione/package.json
packages/allure-jest/package.json

Cleanup package.json

---

.pnp.cjs
.pnp.loader.mjs
packages/allure-vitest/.gitignore
packages/allure-vitest/package.json
packages/allure-vitest/tsconfig.json

update package entries to make typescript able to resolve types declarations
fixes #872 

Fix vitest types declarations

---

packages/allure-vitest/src/reporter.ts
packages/allure-vitest/test/spec/direct/timeline.test.ts

fix(vitest): Add missing hostname label

---

packages/allure-vitest/src/reporter.ts
packages/allure-vitest/src/setup.ts
packages/allure-vitest/src/utils.ts
packages/allure-vitest/test/spec/fullName.test.ts
packages/allure-vitest/test/spec/setup/testPlan.test.ts

set correct suites labels for vitest

[Vitest]: correct  and suites labels

---

packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/test/specs/overview.ts

[Newman]: fix markdown description

---

packages/allure-jest/jest.config.js

Increase Jest tests timeout

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/release.yml

Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases)
https://nodejs.org/en/about/previous-releases

Build using node@18

---

packages/allure-jest/src/AllureJest.ts
packages/allure-jest/test/spec/retry.test.ts
packages/allure-jest/test/utils.ts

Fix allure-jest jest.retryTimes() bug

---

package.json

Disable yarn parallel build

---

packages/allure-cypress/README.md
packages/allure-cypress/src/index.ts
packages/allure-cypress/src/utils.ts
packages/allure-cypress/test/spec/runtime/legacy/attachments.test.ts
packages/allure-cypress/test/spec/runtime/legacy/description.test.ts
packages/allure-cypress/test/spec/runtime/legacy/displayName.test.ts
packages/allure-cypress/test/spec/runtime/legacy/historyId.test.ts
packages/allure-cypress/test/spec/runtime/legacy/labels.test.ts
packages/allure-cypress/test/spec/runtime/legacy/links.test.ts
packages/allure-cypress/test/spec/runtime/legacy/parameters.test.ts
packages/allure-cypress/test/spec/runtime/legacy/steps.test.ts
packages/allure-cypress/test/spec/runtime/legacy/testCaseId.test.ts
packages/allure-cypress/test/spec/runtime/legacy/titleMetadata.test.ts
packages/allure-cypress/test/spec/runtime/modern/attachments.test.ts
packages/allure-cypress/test/spec/runtime/modern/description.test.ts
packages/allure-cypress/test/spec/runtime/modern/displayName.test.ts
packages/allure-cypress/test/spec/runtime/modern/historyId.test.ts
packages/allure-cypress/test/spec/runtime/modern/labels.test.ts
packages/allure-cypress/test/spec/runtime/modern/links.test.ts
packages/allure-cypress/test/spec/runtime/modern/parameters.test.ts
packages/allure-cypress/test/spec/runtime/modern/steps.test.ts
packages/allure-cypress/test/spec/runtime/modern/testCaseId.test.ts
packages/allure-cypress/test/spec/runtime/modern/titleMetadata.test.ts
packages/allure-cypress/test/utils.ts

Back compatibility with old style cypress runtime API

---

packages/allure-cypress/src/model.ts

Small fix for cypress inner types import

---

packages/allure-jest/README.md
packages/allure-jest/src/index.ts
packages/allure-jest/src/model.ts
packages/allure-jest/test/spec/runtime/legacy/attachments.test.ts
packages/allure-jest/test/spec/runtime/legacy/description.test.ts
packages/allure-jest/test/spec/runtime/legacy/historyId.test.ts
packages/allure-jest/test/spec/runtime/legacy/labels.test.ts
packages/allure-jest/test/spec/runtime/legacy/links.test.ts
packages/allure-jest/test/spec/runtime/legacy/parameters.test.ts
packages/allure-jest/test/spec/runtime/legacy/steps.test.ts
packages/allure-jest/test/spec/runtime/legacy/testCaseId.test.ts
packages/allure-jest/test/spec/runtime/modern/attachments.test.ts
packages/allure-jest/test/spec/runtime/modern/description.test.ts
packages/allure-jest/test/spec/runtime/modern/historyId.test.ts
packages/allure-jest/test/spec/runtime/modern/labels.test.ts
packages/allure-jest/test/spec/runtime/modern/links.test.ts
packages/allure-jest/test/spec/runtime/modern/parameters.test.ts
packages/allure-jest/test/spec/runtime/modern/steps.test.ts
packages/allure-jest/test/spec/runtime/modern/testCaseId.test.ts

Back compatibility with old style jest runtime API

---

.github/labeler.yml
README.md

Remove hermione from docs

---

.pnp.cjs
.yarnrc.yml
packages/newman-reporter-allure/package.json
yarn.lock

Bump newman

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/attachments.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/attachments.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/labelOverride.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/labels.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/links.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/parameters.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/steps.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/tags.spec.ts
packages/allure-playwright/test/spec/runtime/modern/attachments.spec.ts
packages/allure-playwright/test/spec/runtime/modern/labelOverride.spec.ts
packages/allure-playwright/test/spec/runtime/modern/labels.spec.ts
packages/allure-playwright/test/spec/runtime/modern/links.spec.ts
packages/allure-playwright/test/spec/runtime/modern/parameters.spec.ts
packages/allure-playwright/test/spec/runtime/modern/steps.spec.ts
packages/allure-playwright/test/spec/runtime/modern/tags.spec.ts
packages/allure-playwright/test/spec/suites.spec.ts

Back compatibility with old style playwright runtime API

---

packages/allure-codeceptjs/README.md
packages/allure-cucumberjs/README.md
packages/allure-jest/README.md
packages/allure-playwright/README.md
packages/allure-vitest/README.md

Links patterns API

---

.yarnrc.yml
packages/newman-reporter-allure/package.json
yarn.lock

Fix newman

---

tsconfig.json

Enable ts comments

---

packages/allure-vitest/src/reporter.ts
packages/allure-vitest/test/spec/categories.test.ts
packages/allure-vitest/test/spec/environmentInfo.test.ts

feat(vitest): add support for env and categories

---

packages/allure-cucumberjs/src/index.ts
packages/allure-cucumberjs/src/model.ts
packages/allure-cucumberjs/src/reporter.ts
packages/allure-cucumberjs/test/fixtures/features/hooks.feature
packages/allure-cucumberjs/test/fixtures/support/failedHooks.cjs
packages/allure-cucumberjs/test/fixtures/support/hooks.cjs
packages/allure-cucumberjs/test/spec/hooks.test.ts

Cucumber hooks fixtures

---

.pnp.cjs
packages/allure-cypress/.eslintrc.cjs
packages/allure-cypress/package.json
packages/allure-cypress/vitest-setup.ts
packages/allure-cypress/vitest.config.ts
yarn.lock

Add allure report for cypress

---

packages/allure-cypress/test/spec/base.test.ts
packages/allure-cypress/test/spec/commands.test.ts
packages/allure-cypress/test/spec/fixtures.test.ts
packages/allure-cypress/test/spec/hooks.test.ts
packages/allure-cypress/test/spec/reporterInstance.test.ts
packages/allure-cypress/test/spec/runtime/legacy/attachments.test.ts
packages/allure-cypress/test/spec/runtime/legacy/description.test.ts
packages/allure-cypress/test/spec/runtime/legacy/displayName.test.ts
packages/allure-cypress/test/spec/runtime/legacy/historyId.test.ts
packages/allure-cypress/test/spec/runtime/legacy/labels.test.ts
packages/allure-cypress/test/spec/runtime/legacy/links.test.ts
packages/allure-cypress/test/spec/runtime/legacy/parameters.test.ts
packages/allure-cypress/test/spec/runtime/legacy/steps.test.ts
packages/allure-cypress/test/spec/runtime/legacy/testCaseId.test.ts
packages/allure-cypress/test/spec/runtime/legacy/titleMetadata.test.ts
packages/allure-cypress/test/spec/runtime/modern/attachments.test.ts
packages/allure-cypress/test/spec/runtime/modern/description.test.ts
packages/allure-cypress/test/spec/runtime/modern/displayName.test.ts
packages/allure-cypress/test/spec/runtime/modern/historyId.test.ts
packages/allure-cypress/test/spec/runtime/modern/labels.test.ts
packages/allure-cypress/test/spec/runtime/modern/links.test.ts
packages/allure-cypress/test/spec/runtime/modern/parameters.test.ts
packages/allure-cypress/test/spec/runtime/modern/steps.test.ts
packages/allure-cypress/test/spec/runtime/modern/testCaseId.test.ts
packages/allure-cypress/test/spec/runtime/modern/titleMetadata.test.ts
packages/allure-cypress/test/spec/screenshots.test.ts
packages/allure-cypress/test/spec/video.test.ts
packages/allure-cypress/test/utils.ts

add test for cyrpess native fixtures
add tests for steps/attachments inside hooks
fixes #1022

Proof of work for cypress native fixtures

---

packages/allure-cypress/src/index.ts
packages/allure-cypress/test/spec/base.test.ts

- feat: cypress report skipped tests - fix lint / prettier
- feat: cypress report skipped tests
- complete cypress skipped tests processing
fixes #948
relates to #949

Add Cypress reports for skipped tests

---

packages/allure-playwright/test/spec/skip.test.ts

chore(allure-playwright): add test for testCaseId for skipped tests

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/package.spec.ts

feat(allure-playwright): add package label

---

packages/allure-cypress/src/index.ts
packages/allure-cypress/src/model.ts
packages/allure-cypress/src/reporter.ts
packages/allure-cypress/src/utils.ts
packages/allure-cypress/test/spec/testplan.test.ts
packages/allure-cypress/test/utils.ts

Cypress test plan support

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/annotations.spec.ts
packages/allure-playwright/test/spec/skip.test.ts

feat(allure-playwright): support skip and fixme annotations

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/tags.spec.ts

feat(allure-playwright): support test tags

---

packages/allure-jest/test/spec/hooks.test.ts

tests(allure-jest): add tests to showcase runtime api usage in hooks

---

packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/test/spec/simple.test.ts

`getSuiteLabel` in updateTest from `utils` is now used instead of duplicating the same code.

chore: newman reuse getSuiteLabel util

---

packages/allure-vitest/src/setup.ts
packages/allure-vitest/src/utils.ts
packages/allure-vitest/test/spec/test-extend.test.ts
packages/allure-vitest/test/spec/testPlan.test.ts

fix(allure-vitest): add support for test.extend

---

packages/allure-codeceptjs/src/index.ts
packages/allure-codeceptjs/src/reporter.ts
packages/allure-cucumberjs/src/model.ts
packages/allure-cypress/src/model.ts
packages/allure-jasmine/src/index.ts
packages/allure-jest/src/model.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/src/sdk/reporter/types.ts
packages/allure-js-commons/test/sdk/reporter/writer/FileSystemWriter.spec.ts
packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-playwright/src/model.ts
packages/allure-vitest/src/reporter.ts
packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/src/model.ts

fix(allure-js-commons): rft reporter configuration type

---

packages/allure-js-commons/src/sdk/reporter/utils/labels.ts

fix(allure-js-commons): add support for workers in default thread label

---

packages/allure-js-commons/src/sdk/utils.ts
packages/allure-vitest/src/reporter.ts
packages/allure-vitest/test/spec/expect-extend.test.ts

fix test statuses for expect.extend errors

---

packages/allure-jest/test/spec/runtime/modern/labels.test.ts
packages/allure-jest/test/spec/runtime/modern/links.test.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/test/sdk/reporter/ReporterRuntime.spec.ts

fix(allure-js-commons): fix hooks metadata processing

---

packages/allure-cucumberjs/src/reporter.ts
packages/allure-cucumberjs/test/samples/features/examples-multi.feature
packages/allure-cucumberjs/test/samples/features/examples-name-change.feature
packages/allure-cucumberjs/test/samples/support/examples-multi.cjs
packages/allure-cucumberjs/test/spec/examples.test.ts
packages/allure-cucumberjs/test/utils.ts

fix(allure-cucumberjs): fix scenario outline reporting

---

packages/allure-jest/src/environmentFactory.ts
packages/allure-jest/test/spec/hooks.test.ts
packages/allure-jest/test/spec/skipped.test.ts
packages/allure-jest/test/spec/snapshot.test.ts
packages/allure-jest/test/spec/todo.test.ts

fix(allure-jest): add support for soft assertions

---

packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-mocha/test/samples/spec/plain-mocha/ansiError.spec.js
packages/allure-mocha/test/spec/framework/errors.test.ts

fix(allure-mocha): strip ansi characters in message & trace

---

packages/allure-cucumberjs/src/reporter.ts
packages/allure-cucumberjs/test/samples/features/errors.feature
packages/allure-cucumberjs/test/samples/support/errors.cjs
packages/allure-cucumberjs/test/spec/errors.test.ts
packages/allure-js-commons/src/sdk/reporter/utils.ts

fix(allure-cucumberjs): add support for playwright assertions

---

packages/allure-jest/package.json

Tried to import `jsdom` from `allure-jest` and discovered that exports pointing to non-existent file.

fix(allure-jest): fix allure-jest broken exports

---

packages/allure-cucumberjs/README.md

Addressed a small typo on line 53. IYou to You.

Update typo to the README.md

---

packages/allure-jest/README.md
packages/allure-jest/package.json
packages/allure-jest/src/environmentFactory.ts
packages/allure-jest/src/jsdom.ts
packages/allure-jest/src/node.ts

feat(allure-jest): allow using Allure with custom environments

---

packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/test/mocks/handlers.ts
packages/newman-reporter-allure/test/spec/port.test.ts

Show the request port in the report if any
fixes #1198

fix(newman): show the port

---

packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/test/sdk/reporter/ReporterRuntime.spec.ts

fixes https://github.com/allure-framework/allure-js/issues/1230

fix history id calculation for hook parameters

---

packages/allure-codeceptjs/src/model.ts
packages/allure-codeceptjs/src/reporter.ts
packages/allure-codeceptjs/test/spec/bdd.test.ts
packages/allure-codeceptjs/test/spec/labels.test.ts

feat(codeceptjs) add support for bdd steps

---

packages/allure-jest/src/environmentFactory.ts
packages/allure-jest/test/spec/errors.test.ts
packages/allure-js-commons/src/sdk/utils.ts

fix(jest): better support for jest test errors

---

packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/src/sdk/reporter/index.ts
packages/allure-js-commons/src/sdk/reporter/utils.ts
packages/allure-js-commons/test/sdk/reporter/ReporterRuntime.spec.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/src/utils.ts
packages/allure-playwright/test/spec/hooks.spec.ts

Fix playwright step statuses and tests structure

---

packages/allure-playwright/test/spec/attachments.spec.ts

Add tests for playwright trace attachments

---

.pnp.cjs
packages/allure-js-commons/src/model.ts
packages/allure-js-commons/src/sdk/index.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/src/model.ts
packages/allure-playwright/src/utils.ts
packages/allure-playwright/test/spec/hooks.spec.ts

Playwright hook attachments (fix #1278)

---

packages/allure-cypress/src/browser/commandLog.ts
packages/allure-cypress/src/browser/utils.ts
packages/allure-cypress/src/types.ts
packages/allure-cypress/test/spec/commands.test.ts

cypress: fix crashing if renderProps doesn't exist
