allure-framework/allure-js

packages/allure-mocha/src/AllureReporter.ts
packages/allure-mocha/src/MochaAllureReporter.ts
packages/allure-mocha/test/fixtures/specs/nested.ts
packages/allure-mocha/test/fixtures/specs/pending.ts
packages/allure-mocha/test/specs/common.ts
packages/allure-mocha/test/specs/feature.ts
packages/allure-mocha/test/specs/nesting.ts
packages/allure-mocha/test/specs/owner.ts
packages/allure-mocha/test/specs/severity.ts
packages/allure-mocha/test/specs/story.ts
packages/allure-mocha/test/specs/tag.ts
packages/allure-mocha/test/utils/index.ts
tsconfig.json

Suites nesting

---

package.json
packages/allure-mocha/README.md
packages/allure-mocha/index.ts
packages/allure-mocha/package.json
packages/allure-mocha/runtime.d.ts
packages/allure-mocha/runtime.js
packages/allure-mocha/src/AllureReporter.ts
packages/allure-mocha/src/MochaAllureReporter.ts
packages/allure-mocha/src/index.ts
packages/allure-mocha/test/fixtures/specs/attachment.ts
packages/allure-mocha/test/fixtures/specs/description.ts
packages/allure-mocha/test/fixtures/specs/feature.ts
packages/allure-mocha/test/fixtures/specs/globalInfo.ts
packages/allure-mocha/test/fixtures/specs/hooks.ts
packages/allure-mocha/test/fixtures/specs/issueAndTms.ts
packages/allure-mocha/test/fixtures/specs/owner.ts
packages/allure-mocha/test/fixtures/specs/parameter.ts
packages/allure-mocha/test/fixtures/specs/severity.ts
packages/allure-mocha/test/fixtures/specs/step.ts
packages/allure-mocha/test/fixtures/specs/story.ts
packages/allure-mocha/test/fixtures/specs/tag.ts
packages/allure-mocha/test/runner.ts
packages/allure-mocha/test/tsconfig.json
packages/allure-mocha/test/utils/index.ts
packages/allure-mocha/tsconfig.json

closes #37 
1. Added a new top level file `allure-mocha/runtime` that customers should import to access `allure` object.
2. Created a separate typescript project for test files, this was needed to make local imports `import { allure } from "../../../runtime";` working correctly.
3. Disabled `ignoreLeaks` option in Mocha. This confirms that the fix is working

Implement importable runtime API

---

packages/allure-mocha/.npmignore

In the https://github.com/allure-framework/allure-js/pull/46 I added a new file to the module –`runtime.js`.
But I forgot to update npmignore to make it actually published.
How I tested this: 
1. ran `npm pack`, checked the output: 
```
npm notice
npm notice 📦  allure-mocha@2.0.0-beta.5
npm notice === Tarball Contents ===
npm notice 1.7kB  package.json
npm notice 11.3kB LICENSE.txt
npm notice 1.3kB  README.md
npm notice 53B    runtime.d.ts
npm notice 578B   runtime.js
npm notice 993B   dist/AllureReporter.d.ts
npm notice 4.1kB  dist/AllureReporter.js
npm notice 3.8kB  dist/AllureReporter.js.map
npm notice 91B    dist/index.d.ts
npm notice 171B   dist/index.js
npm notice 138B   dist/index.js.map
npm notice 791B   dist/MochaAllureInterface.d.ts
npm notice 2.2kB  dist/MochaAllureInterface.js …
```

update npmignore to include new files into published artifact

---

packages/allure-js-commons/src/AllureGroup.ts
packages/allure-js-commons/src/AllureTest.ts
packages/allure-js-commons/src/ExecutableItemWrapper.ts

* Useful when converting other report formats to allure, in which case time should be read from files instead of `Date.now()`
* This patch is backward compatible

allow to override test & step timestamp

---

packages/allure-cucumberjs/src/CucumberAllureInterface.ts
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-jasmine/src/JasmineAllureReporter.ts
packages/allure-js-commons/index.ts
packages/allure-js-commons/src/Allure.ts
packages/allure-js-commons/src/AllureRuntime.ts
packages/allure-js-commons/src/ExecutableItemWrapper.ts
packages/allure-js-commons/src/model.ts
packages/allure-js-commons/src/writers/utils.ts
packages/allure-mocha/src/AllureReporter.ts
packages/allure-mocha/src/MochaAllure.ts
packages/allure-mocha/test/fixtures/specs/attachment.ts
packages/allure-mocha/test/specs/attachments.ts

This is the Javascript integration for this feature: https://github.com/allure-framework/allure2/pull/1145
Currently only pre-defined content types are supported, this PR adds custom types:
```js
allure.attachment('screen diff', screenDiffJson, {
contentType: 'application/vnd.allure.image.diff',
fileExtension: 'json' // no auto-detect, because `file-type` npm module has async API, but our method is sync
})
```

feat: Support custom attachment content types

---

packages/allure-cucumberjs/README.md
packages/allure-cucumberjs/features/links.feature
packages/allure-cucumberjs/features/step_definitions/report.steps.ts
packages/allure-cucumberjs/src/CucumberAllureInterface.ts
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-js-commons/src/AllureTest.ts

Currently, with the new version, it is not possible to link test results with issue tracker tools, like JIRA or XRAY

Add ability to link test results with issues and tms.

---

packages/allure-jasmine/test/helpers.ts

Currently the build in the `master` branch fails, because of changes in the `@types/jasmine` dependency. This PR fixes that

fix jasmine type definitions

---

README.md
packages/allure-playwright/.gitignore
packages/allure-playwright/.npmignore
packages/allure-playwright/LICENSE.txt
packages/allure-playwright/README.md
packages/allure-playwright/package.json
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/fixtures.ts
packages/allure-playwright/test/labels.spec.ts
packages/allure-playwright/test/status-details.spec.ts
packages/allure-playwright/test/status.spec.ts
packages/allure-playwright/test/stdio.spec.ts
packages/allure-playwright/tsconfig.json

Fixes https://github.com/allure-framework/allure-js/issues/296, https://github.com/microsoft/playwright/issues/7034
This is initial implementation for Playwright reporter. I already booked `allure-playwright` npm package for it, please let me know who I should transfer ownership over it to. I did not push that package.
Please let me know what you think about it and I can add more tests for it.

feat(allure-playwright): initial implementation for allure-playwright

---

packages/allure-js-commons/src/AllureRuntime.ts
packages/allure-js-commons/src/writers/AllureWriter.ts
packages/allure-js-commons/src/writers/FileSystemAllureWriter.ts
packages/allure-js-commons/src/writers/InMemoryAllureWriter.ts
packages/allure-playwright/src/index.ts

fixes #326
the change also intruduces new API methods:
```js
AllureRuntime#writeAttachmentFromPath(string, PathLike);
AllureWriter#writeAttachmentFromPath(string, PathLike);
```

Fix playwright path attachments

---

packages/allure-playwright/package.json
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/attachment.spec.ts

Some of the attachments may be deleted bu the runner (e.g. `video: on, preserveOutput: 'failures-only'` test config) or clients could add non-existing path as attachment.
Fixes https://github.com/microsoft/playwright/issues/8611

fix(playwright): do not throw if cannot copy attachment from given path

---

packages/allure-js-commons/src/model.ts
packages/allure-js-commons/src/writers/utils.ts

Original report: https://github.com/microsoft/playwright/issues/8611
This is the exception that the user gets:

fix: support application/zip in typeToExtension

---

packages/allure-mocha/src/MochaAllureReporter.ts

Fixed the edge case when `reporterOptions` can be missing by adding an alternative empty object, which can be correctly destructured with a default value to `resultsDir`.
Fixes #430 

fix(mocha): add an additional check for missing reporterOptions

---

packages/allure-cucumberjs/README.md
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/helpers/formatter_helpers.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts

fixes #456
Provides a new API for `links` processing. Now, the related config part looks in this way:
```diff
export default class Reporter extends CucumberJSAllureFormatter {
constructor(options) {
super(
options,
new AllureRuntime({ resultsDir: "./allure-results" }),
{
labels: {
epic: [/@feature:(.*)/],
severity: [/@severity:(.*)/]
},
-        links: {
-          issues: {
-            pattern: [/@issue=(.*)/],
-            urlTemplate: "http://localhost:8080/issue/%s"
-          },
-          tms: {
-            pattern: [/@tms=(.*)/],
-            urlTemplate: "http://localhost:8080/tms/%s"
-          }
-        }
+        links: [
+          {
+            pattern: [/@issue=(.*)/],
+            type: "issue",
+            urlTemplate: "http://localhost:8080/issue/%s"
+          },
+ …
```

feat(cucumberjs): extract links and labels from tags

---

.gitignore

Updates `.gitignore` for `allure-results` and `.nyc-output` directories

Ignore `.nyc-output` files

---

packages/allure-cucumberjs/package.json
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts
yarn.lock

Add host and thread labels for cucumberjs (fixes #454)

---

.github/release-drafter.yml
.github/workflows/labels-verify.yml
packages/allure-playwright/README.md

chore(playwright) Readme improvements for screenshots, attachments, steps

---

packages/allure-mocha/src/AllureReporter.ts
packages/allure-mocha/test/fixtures/specs/package.ts
packages/allure-mocha/test/specs/package.ts

fixes #460
Adds `package` label for mocha specs. According another allure implementations, package now is a path to spec file

Add package label for mocha specs

---

packages/allure-playwright/src/index.ts

closes #479 https://github.com/microsoft/playwright/issues/14706
before:
after:

feat(playwright): add thread label and host labels

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts

fixes #492
Use `process.pid` as fallback value for `THREAD` label

fix cucumberjs reporter on windows

---

packages/allure-mocha/src/AllureReporter.ts
packages/allure-mocha/src/MochaAllureReporter.ts
packages/allure-mocha/test/specs/hooks.ts

Uses `title` instead of `originalTitle` for mocha hooks to visually simplify dependency between hooks and specs.
Additionally fixes the problem with `hook.error is not a function`.
fixes #424 
**Before**
**After**

Better titles for mocha hooks

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts

split pr https://github.com/allure-framework/allure-js/pull/546
When I switched to allure in cucumber v8, I encountered a number of problems that were not repeated in cucumber v6:
- Attachments with the datatable are placed at the end of the test, not under the expected step. This is very unattractive if the test has several datatables. Previously, in Cucumber 6, they were placed under each step.
some pictures with changes:
**problem before fix:**
**problem after fix:**

fix(cucumberjs): attach a datable to the step

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts

split pr #546
When I switched to allure in cucumber v8, I encountered a number of problems that were not repeated in cucumber v6:
1) I can't install my CustomWorld, although the [documentation](https://github.com/allure-framework/allure-js/tree/master/packages/allure-cucumberjs#using-allure-api) has information about it. The reason is that the formatter explicitly sets CucumberAllureWorld after we specify our custom constructor

fix(cucumberjs): fix setup custom world

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/allure_cucumberjs_test.ts

split pr #546
When I switched to allure in cucumber v8, I encountered a number of problems that were not repeated in cucumber v6:
- When using '--repeat', tests were duplicated instead of being placed in the history 
some pictures with changes:
**problem before fix:**
**problem after fix:**

fix(cucumberjs): grouping of retried tests

---

packages/allure-js-commons/package.json
packages/allure-js-commons/src/writers/FileSystemAllureWriter.ts
packages/allure-js-commons/test/specs/FileSystemAllureWriter.spec.ts
yarn.lock

`fs.mkdirSync(path, {recursive:true})` doing the same thing without any packages

chore(commons): delete mkdirp package

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/categories.spec.ts
packages/allure-playwright/test/environmentInfo.spec.ts
packages/allure-playwright/test/fixtures.ts

This PR add categories and enviormentInfo support.
This fields setted via `playwright.config.ts` file
```diff
export default {
reporter: [
[
"allure-playwright",
{
+        environmentInfo: {
+         envVar1: "envVar1Value",
+         envVar2: "envVar2Value",
+       },
+       categories: [
+          {
+           name: "Infrastructure problems",
+           messageRegex: ".*RuntimeException.*",
+           matchedStatuses: ["broken"],
+         },
+      ],
},
],
],
projects: [
{
name: "chromium",
},
],
};
```

feature(playwright): Add `categories` and `environmentInfo` support to playwright

---

packages/allure-js-commons/src/Allure.ts

This staff is deprecated for like 4 years so i guess its time to delete it

chore(commons): delete deprecated `createStep` and `createAttachment` from commons

---

packages/allure-cucumberjs/README.md
packages/allure-cucumberjs/src/CucumberAllureWorld.ts
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-hermione/README.md
packages/allure-hermione/src/index.ts
packages/allure-hermione/test/fixtures/parameter.js
packages/allure-hermione/test/spec/parameters.test.ts
packages/allure-js-commons/src/AllureCommandStep.ts
packages/allure-js-commons/src/model.ts
packages/allure-js-commons/test/specs/AllureCommandStep.spec.ts
packages/allure-mocha/README.md
packages/allure-playwright/README.md
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/parameters.spec.ts

Previously format of parameters in `allure-js` was wrong and `hidden` option didn't work properly

fix(commons): fix parameters modes

---

packages/allure-codeceptjs/README.md
packages/allure-codeceptjs/src/helpers.ts
packages/allure-codeceptjs/src/index.ts
packages/allure-codeceptjs/test/codecept-tags.test.ts
packages/allure-js-commons/index.ts
packages/allure-js-commons/src/utils.ts
packages/newman-reporter-allure/src/helpers.ts

The objective of this PR is to be able to manage the labels of pace via tags on the codeceptjs scenario.
for example:
```js
Scenario('taggs', () => { 
// my test
}).tag('@slow')
.tag('important')
.tag('@owner:eroshenkoam')
.tag('@layer:UI')
.tag('@id:228')
.tag('@story:aga')
.tag('@epic:aga')
.tag('@severity:critical');
```

feature(codeceptjs): feature to pass allure metadata through сodeceptjs tags

---

packages/allure-js-commons/src/utils.ts
packages/allure-js-commons/test/specs/utils.spec.ts

It is not possible to make scoped tags. comme `env:dev` or `env:prod`.
This PR corrects the regex to support scoped tags.
Before when I have `@allure.label.tag=env:prod`, that doesn't works, because the name of the label was `tag=env` and the value was `prod`.
With this PR, now, the label is `tag` and the value is `env:prod`

Added support for scoped tags

---

packages/allure-js-commons/src/AllureCommandStep.ts
packages/allure-js-commons/test/specs/AllureCommandStep.spec.ts

in 2.2.0 release `AllureStepCommand.start()` method was deleted. This
change adds the method back

Fix breaking change introduced in 2.2.0

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/attachments_test.ts

Closes #688
Please check linked issue to get more information about the problem
Allure attachments are place outside the cucumber steps

fix(cucumberjs): support steps' attachments 

---

packages/allure-cucumberjs/README.md
packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/simple_test.ts

This fixes cross-browser testing in Cucumber - currently results from multiple browsers land in Retries tab. 
History ID must be calculated based on added parameters for this to work. 
The fix is based on Playwright reporter implementation: 
https://github.com/allure-framework/allure-js/blob/38366df3346bd8428f99c539af9f881d36de34b9/packages/allure-playwright/src/index.ts#L272

Enable cross-browser testing in Cucumber reporter

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-hermione/src/index.ts
packages/allure-hermione/src/utils.ts
packages/allure-hermione/test/fixtures/historyId.js
packages/allure-hermione/test/fixtures/testCaseId.js
packages/allure-hermione/test/spec/historyId.test.ts
packages/allure-hermione/test/spec/steps.test.ts
packages/allure-hermione/test/spec/testCaseId.test.ts
packages/allure-js-commons/src/AllureTest.ts
packages/allure-js-commons/src/model.ts

fixes #747 
- Adds ability to set `testCaseId` and `historyId` manually.
- Fixes problem with lack of `testCaseId` for `hermione`
- Introduces new test method to parse and apply metadata messages and uses the method for `hermione` and `cucumber` integrations

History ID and metadata processing improvements

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/with_labels_test.ts
packages/allure-cucumberjs/test/specs/with_links_test.ts

Currently, on my Cucumber test repository, we are using the `Rule` keyword to group subscenarios on a `Feature`. However, we noticed that "tags as labels/links" (such as `@severity:critical`, `@issue=3` and `@feature:foo` ) are not being parsed by `Scenario`, only by `Feature`.
**Test outside rule:**
**Test inside rule:**
After debugging, we've found out that the report does not parse scenario's labels/links when they are under a `Rule`. I don't know if this is a known problem, but, as a token of gratitude for the open source community, I am sending a PR myself to address this issue if you like it :)
PS: I've updated the tests as well.

fix(cucumber): add support for rule keyword

---

packages/allure-cucumberjs/src/CucumberJSAllureReporter.ts
packages/allure-cucumberjs/test/specs/description_test.ts

Add better description handler for cucumber features

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/history.spec.ts

Fixes #732 
When the suite name is excluded from the source for the testCaseId hash, tests that are parametrized at the 'test.describe' level erroneously end up with duplicate testCaseIds.

Include suite name in Playwright testCaseId md5 hash (fixes #732)

---

packages/allure-hermione/src/index.ts
packages/allure-hermione/test/fixtures/only.js
packages/allure-hermione/test/spec/only.test.ts

Change skipped tests handling logic

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/attachment-steps.spec.ts

When the `detail: true` option is set, Allure logs the `attach` steps. But since we already have attachments in the report such messages are nothing but noise. The proposed change disables reporting of `attach` steps completely.

impr(playwright): disable reporting of attach steps

---

packages/allure-jest/README.md
packages/allure-jest/src/AllureJest.ts

Provides `resultsDir` configuration for jest reporter
Now it's impossible to configure anything for jest reporter, but some options, like `resultsDir` are critical and should be available for users 

Add ability to configure jest reporter

---

packages/allure-jest/src/AllureJestApi.ts
packages/allure-jest/test/fixtures/attachments.test.js
packages/allure-jest/test/spec/attachments.test.ts
packages/allure-js-commons/src/AllureTest.ts

Add ability to assign custom names for any attachments #801

feat(allure-jest): Add ability to assign custom names for any attachments (feat #801)

---

README.md
packages/allure-codeceptjs/README.md
packages/allure-cucumberjs/README.md
packages/allure-decorators/README.md
packages/allure-hermione/README.md
packages/allure-jasmine/README.md
packages/allure-jest/README.md
packages/allure-js-commons/README.md
packages/allure-mocha/README.md
packages/allure-playwright/README.md
packages/newman-reporter-allure/README.md

The PR wraps each Allure logo in the README files in the URL of allurereport.org.

Change plain logos in the README files into URLs

---

packages/allure-vitest/README.md
packages/allure-vitest/package.json
packages/allure-vitest/src/index.ts
packages/allure-vitest/src/setup.ts
packages/allure-vitest/test/spec/setup/attachments.test.ts
packages/allure-vitest/test/spec/setup/description.test.ts
packages/allure-vitest/test/spec/setup/displayName.test.ts
packages/allure-vitest/test/spec/setup/historyId.test.ts
packages/allure-vitest/test/spec/setup/labels.test.ts
packages/allure-vitest/test/spec/setup/links.test.ts
packages/allure-vitest/test/spec/setup/parameters.test.ts
packages/allure-vitest/test/spec/setup/steps.test.ts
packages/allure-vitest/test/spec/setup/testCaseId.test.ts
packages/allure-vitest/test/utils.ts
packages/allure-vitest/tsconfig.json
packages/allure-vitest/vitest.config.ts

Fix vitest files resolving

---

packages/allure-vitest/src/reporter.ts
packages/allure-vitest/test/spec/direct/timeline.test.ts

fix(vitest): fix test duration and hostname

---

packages/allure-vitest/src/index.ts
packages/allure-vitest/src/reporter.ts
packages/allure-vitest/src/setup.ts
packages/allure-vitest/test/spec/direct/timeline.test.ts

fix(vitest): fix thread id for tests

---

packages/allure-vitest/src/reporter.ts

change vitests test duration to match this https://github.com/vitest-dev/vitest/pull/5219

fix(vitest): calculate full duration

---

packages/allure-vitest/src/reporter.ts

fixes #899
I decided to get rid of the complicated logic of test duration calculation in favour of native test duration.
**Vitest output**
**Allure report**

[Vitest] Use actual test duration

---

packages/allure-jasmine/README.md
packages/allure-jasmine/src/index.ts
packages/allure-jasmine/test/fixtures/spec/helpers/legacy/allure.cjs
packages/allure-jasmine/test/fixtures/spec/helpers/modern/allure.cjs
packages/allure-jasmine/test/fixtures/spec/support/jasmine.json
packages/allure-jasmine/test/spec/runtime/legacy/attachments.test.ts
packages/allure-jasmine/test/spec/runtime/legacy/description.test.ts
packages/allure-jasmine/test/spec/runtime/legacy/historyId.test.ts
packages/allure-jasmine/test/spec/runtime/legacy/labels.test.ts
packages/allure-jasmine/test/spec/runtime/legacy/links.test.ts
packages/allure-jasmine/test/spec/runtime/legacy/parameters.test.ts
packages/allure-jasmine/test/spec/runtime/legacy/steps.test.ts
packages/allure-jasmine/test/spec/runtime/legacy/testCaseId.test.ts
packages/allure-jasmine/test/spec/runtime/modern/attachments.test.ts
packages/allure-jasmine/test/spec/runtime/modern/description.test.ts
packages/allure-jasmine/test/spec/runtime/modern/historyId.test.ts
packages/allure-jasmine/test/spec/runtime/modern/labels.test.ts
packages/allure-jasmine/test/spec/runtime/modern/links.test.ts
packages/allure-jasmine/test/spec/runtime/modern/parameters.test.ts
packages/allure-jasmine/test/spec/runtime/modern/steps.test.ts
packages/allure-jasmine/test/spec/runtime/modern/testCaseId.test.ts
packages/allure-jasmine/test/spec/simple.test.ts
packages/allure-jasmine/test/utils.ts

- add back compatibility with old-style jasmine runtime api
- fix linters issues

Back compatibility with old style jasmine runtime API

---

packages/allure-js-commons/src/sdk/TestPlan.ts
packages/allure-js-commons/src/sdk/node/TestPlan.ts
packages/allure-js-commons/src/sdk/node/index.ts
packages/allure-playwright/package.json
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/history.spec.ts
packages/allure-playwright/test/spec/skip.test.ts
packages/allure-playwright/test/spec/testplan.spec.ts

impr(playwright): new fullname format and improved test plan support

---

packages/allure-js-commons/src/sdk/node/writers/FileSystemAllureWriter.ts
packages/allure-js-commons/test/spec/FileSystemAllureWriter.spec.ts

Ensure results dir created before write result

---

packages/allure-codeceptjs/src/reporter.ts
packages/allure-codeceptjs/test/spec/hooks.test.ts
packages/allure-codeceptjs/test/spec/simple.test.ts

CodeceptJS hooks fixtures

---

packages/allure-mocha/package.json
packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-mocha/src/utils.ts
packages/allure-mocha/test/fixtures/reporter.cjs
packages/allure-mocha/test/fixtures/runner.js
packages/allure-mocha/test/fixtures/samples/labels/meta/change.spec.js
packages/allure-mocha/test/fixtures/samples/labels/meta/id/1004.spec.js
packages/allure-mocha/test/fixtures/samples/labels/meta/id/1005.spec.js
packages/allure-mocha/test/fixtures/samples/labels/meta/multiple.spec.js
packages/allure-mocha/test/fixtures/samples/labels/meta/single.spec.js
packages/allure-mocha/test/spec/api/metadata.test.ts
packages/allure-mocha/test/spec/api/testplan.test.ts
packages/allure-mocha/test/spec/config.test.ts
packages/allure-mocha/test/spec/framework/result.test.ts
packages/allure-mocha/test/utils.ts
packages/allure-mocha/vitest.config.mts

Add test plan support to Allure Mocha.
- dump the environment info and categories when the test run is done
- allure metadata (labels and a shorthand for ALLURE_ID) can now be specified via a test's name. That doesn't affect testCaseId and display name:
```js
it("my test @allure.id:1001 @allure.label.owner:John", () => { /* ... */ });
```
That's crucial for filtering by ID via a test plan.
- hook timeout was increased when testing Allure Mocha (some combinations take around 10 seconds to complete on my machine - the default hook timeout value)
- Redundant host and thread labels calculation was removed from allure-mocha. Allure-js-commons is used now.

Allure Mocha: testplan support, env info and categories, metadata

---

packages/allure-codeceptjs/test/spec/runtime/legacy/links.test.ts
packages/allure-codeceptjs/test/spec/runtime/modern/links.test.ts
packages/allure-cucumberjs/src/model.ts
packages/allure-cucumberjs/src/reporter.ts
packages/allure-cucumberjs/test/utils.ts
packages/allure-cypress/src/reporter.ts
packages/allure-cypress/test/utils.ts
packages/allure-jasmine/test/fixtures/spec/helpers/legacy/allure.cjs
packages/allure-jasmine/test/fixtures/spec/helpers/modern/allure.cjs
packages/allure-jest/test/utils.ts
packages/allure-js-commons/src/model.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/src/sdk/reporter/types.ts
packages/allure-js-commons/src/sdk/reporter/utils.ts
packages/allure-js-commons/test/sdk/reporter/ReporterRuntime.spec.ts
packages/allure-js-commons/test/sdk/reporter/utils/links.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/links.spec.ts
packages/allure-playwright/test/spec/runtime/modern/links.spec.ts
packages/allure-vitest/test/utils.ts

The PR changes the link patterns configuration type from the array to the record whose keys are either `LinkType` values or arbitrary strings. A link's template can now be an arbitrary function from `string` to `string`. `LinkConfig` is now defined as follows:
```ts
export type LinkConfig<TOpts extends LinkTypeOptions = LinkTypeOptions> =
Partial<Record<LinkType, TOpts>> & Record<string, TOpts>;
```
1. A generic type argument is used to allow integrations to extend link options. Allure-cucumber does that to add an extra `pattern` field to the options.
2. Defining the config as an intersection allows us to:
- keep IDE autocompletion
- index the values with arbitrary string keys (TS infers the resulting type to be `TOpts` instead of `TOpts | undefined` in such cases, but that's how it works …

Change link template config type from an array to a record. Support link template functions

---

.pnp.cjs
packages/allure-cucumberjs/.eslintrc.cjs
packages/allure-cucumberjs/package.json
packages/allure-cucumberjs/test/utils.ts
packages/allure-cucumberjs/vitest-setup.ts
packages/allure-cucumberjs/vitest.config.ts
yarn.lock

Add report for allure-cucumberjs package

---

.pnp.cjs
packages/allure-mocha/.eslintrc.cjs
packages/allure-mocha/package.json
packages/allure-mocha/test/spec/framework/result.test.ts
packages/allure-mocha/test/utils.ts
packages/allure-mocha/vitest-setup.ts
packages/allure-mocha/vitest.config.mts
yarn.lock

Add report for allure-mocha package

---

packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-mocha/test/fixtures/samples/labels/skippedAtRuntime.spec.js
packages/allure-mocha/test/fixtures/samples/legacy/labels/skippedAtRuntime.spec.js
packages/allure-mocha/test/spec/defects/dynamicSkip.spec.ts
packages/allure-mocha/test/utils.ts
packages/allure-mocha/vitest.config.mts

If a test is skipped at runtime (with `this.skip();`), the test result gets overwritten, and all the data (links, labels, etc) is lost.
In such cases, `onTest` is called before `onPending` so there is no need to create a new test result.
Also, we might want to implement a countermeasure of some sort (a warning or an error) if we dismiss the currently running test result.
- Issue template was added for allure-mocha.
- The runner parameter is now added to allure-mocha test results (we test against three types of runners: the CLI runner and two code runners, in the CommonJS and ESM formats).
Fixes #457

Allure-mocha: fix test result overwritten when a test is skipped dynamically

---

packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-mocha/src/types.ts
packages/allure-mocha/src/utils.ts
packages/allure-mocha/test/fixtures/samples/fixtures/afterEachTwoTests.spec.js
packages/allure-mocha/test/spec/defects/duplicatedAfterEach.spec.ts

The PR fixes afterEach fixtures being associated with all tests in the suite, which leads to multiple afterEach entries in the Tear Down section in the report. That was because we incorrectly assumed the following sequence of Mocha events:
```
onSuite
onTest
onHook (beforeEach)
onHookEnd (beforeEach)
onTestPassed
onHook (afterEach)
onHookEnd (afterEach)
onTestEnd
onSuiteEnd
```
The PR makes allure-mocha support the actual sequence:
```
onSuite
onTest
onHook (beforeEach)
onHookEnd (beforeEach)
onTestPassed
onTestEnd
onHook (afterEach)
onHookEnd (afterEach)
onSuiteEnd
```
This is done by storing the test's scope until `onSuiteEnd`, where scopes of all the suite's tests are written.
Fix #236

Fix duplicated afterEach (#236)

---

packages/allure-cypress/src/index.ts
packages/allure-cypress/src/reporter.ts
packages/allure-cypress/src/utils.ts
packages/allure-cypress/test/spec/commands.test.ts

fix problem with buffer to support cucumber cypress preprocessor
Unfortunately, it's impossible to test cucumber preprocessor right in the project due to yarn pnp dependencies resolution.
See examples here:
- cjs: https://github.com/epszaw/allure-js-3-examples/tree/master/cypress-cucumber-cjs-javascript
- esm: https://github.com/epszaw/allure-js-3-examples/tree/master/cypress-cucumber-esm-javascript

Cypress cucumber preprocessor support

---

packages/allure-cucumberjs/src/reporter.ts

As described in #999 and comments to it, allure-cucumberjs adds the `suite` label with value of `scenario.name`, which makes no sense in both cases:
- if a user sets their own suite, they get a duplicate in the report due to 2 `suite` labels;
- otherwise (since scenario names are unique), it creates an excessive level of nesting: suite has the same name as the only element in it, see the screen in the original issue.

Don't add extra suite label in allure-cucumberjs to fix #999

---

packages/allure-cypress/src/index.ts
packages/allure-cypress/test/spec/runtime/modern/attachments.test.ts
packages/allure-cypress/test/spec/runtime/modern/description.test.ts
packages/allure-cypress/test/spec/runtime/modern/displayName.test.ts
packages/allure-cypress/test/spec/runtime/modern/historyId.test.ts
packages/allure-cypress/test/spec/runtime/modern/labels.test.ts
packages/allure-cypress/test/spec/runtime/modern/links.test.ts
packages/allure-cypress/test/spec/runtime/modern/parameters.test.ts
packages/allure-cypress/test/spec/runtime/modern/steps.test.ts
packages/allure-cypress/test/spec/runtime/modern/testCaseId.test.ts
packages/allure-cypress/test/spec/runtime/modern/titleMetadata.test.ts
packages/allure-js-commons/src/facade.ts
packages/allure-js-commons/src/index.ts
packages/allure-js-commons/src/sdk/runtime/MessageTestRuntime.ts
packages/allure-js-commons/src/sdk/runtime/NoopTestRuntime.ts
packages/allure-js-commons/src/sdk/runtime/types.ts
packages/allure-js-commons/test/facade.spec.ts
packages/allure-js-commons/test/sdk/runtime/MessageTestRuntime.spec.ts
packages/allure-playwright/src/runtime.ts
packages/allure-playwright/test/spec/runtime/modern/steps.spec.ts

```ts
import { logStep, type Status } from "allure-js-commons";
// and the usage
await logStep("passed log step");
await logStep("failed log step", Status.FAILED);
await logStep("broken log step with error", Status.BROKEN, new Error("additional error details"));
```

feat(commons): add logStep Runtime API

---

packages/allure-codeceptjs/src/reporter.ts
packages/allure-codeceptjs/test/spec/globalLabels.test.ts
packages/allure-cucumberjs/src/reporter.ts
packages/allure-cucumberjs/test/spec/globalLabels.test.ts
packages/allure-cucumberjs/test/utils.ts
packages/allure-cypress/src/reporter.ts
packages/allure-cypress/test/spec/globalLabels.test.ts
packages/allure-jasmine/src/index.ts
packages/allure-jasmine/test/spec/globalLabels.test.ts
packages/allure-jasmine/test/utils.ts
packages/allure-jest/src/environmentFactory.ts
packages/allure-jest/test/spec/globalLabels.test.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/globalLabels.test.ts
packages/newman-reporter-allure/package.json
packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/test/spec/globalLabels.test.ts

Global labels support

---

packages/allure-cypress/README.md
packages/allure-cypress/src/model.ts
packages/allure-cypress/src/reporter.ts
packages/allure-cypress/test/spec/video.test.ts

Allow to attach Cypress videos for failed specs only

---

packages/allure-cucumberjs/src/reporter.ts
packages/allure-jest/src/environmentFactory.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/test/sdk/reporter/ReporterRuntime.spec.ts
packages/allure-playwright/src/index.ts
packages/allure-vitest/src/reporter.ts

The pull request introduces the possibility to specify duration instead
of stop timestamp for all stop method in ReporterRuntime. 
Also it fixes timings in jest, vitest and cucumberjs

fix test timings

---

packages/allure-jest/src/environmentFactory.ts
packages/allure-jest/test/spec/hooks.test.ts

The PR fixes two defects in allure-jest hooks:
1. `beforeEach` and `afterEach` hooks are reported for all tests in the suite.
In the following example, the tests receive two fixtures each:
```js
beforeEach(() => {});
it("foo", () => {});
it("bar", () => {});
```
2. `beforeAll` and `afterAll` hooks aren't reported for tests in the sub-suites.
In the following example, the test receives no fixture:
```js
beforeAll(() => {});
describe("foo", () => {
it("bar", () => {});
});
```

fix(allure-jest): beforeEach/afterEach affect all tests in the suite, beforeAll/afterAll don't affect tests in sub-suites

---

packages/allure-jest/package.json
packages/allure-jest/src/environmentFactory.ts
packages/allure-jest/src/jsdom.ts
packages/allure-jest/src/model.ts
packages/allure-jest/src/node.ts
packages/allure-jest/src/utils.ts
yarn.lock

The PR extends the range of supported Jest versions to `>=24.8.0`. Versions before 24.8.0 aren't supported because they ignore an environment's `handleTestEvent` method.
> [!NOTE]
> When using Jest lower than 27.0.0, the `testRunner: "jest-circus/runner"` must be specified in the config. That's why I've added `jest-circus` as an optional peer dependency. Starting from 27.0.0, Jest uses `jest-circus` by default without the need to install it separately.
The main motivation for the change is that older versions (especially 27) still have quite notable download counts:
Fixes #1010

feat(allure-jest): compatibility with Jest >=24.8.0

---

packages/newman-reporter-allure/README.md

https://github.com/allure-framework/allure-js/issues/992
The better solution would've been to allow both for backwards compatibility
Old: --reporter-allure-export
New: --reporter-allure-reportDir

fix(newman-reporter-allure): Update README.md - change flag export to reportDir (fixes #992)

---

.pnp.cjs
packages/allure-jasmine/babel.cjs.json
packages/allure-jasmine/package.json
packages/allure-jasmine/src/index.ts
packages/allure-jasmine/src/model.ts
packages/allure-jasmine/src/testplan.ts
packages/allure-jasmine/src/utils.ts
packages/allure-jasmine/test/spec/hooks.test.ts
packages/allure-jasmine/test/spec/metadata.test.ts
packages/allure-jasmine/test/spec/testplan.test.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/src/sdk/reporter/testplan.ts
packages/allure-js-commons/test/sdk/reporter/testplan.spec.ts
yarn.lock

The PR implements the selective run feature in allure-jasmine.
The implementation is based on wrapping the built-in `describe` and `it` functions and replacing `it` with `xit` for test plan disabled tests. That way we don't have to deal with extra `afterEach` calls, which would occur if we skip tests with `global.pending` instead.
- add name metadata support (required for selective run by Allure ID)
- `addSkipLabel`, `addSkipLabelAsMeta`, and `hasSkipLabel` added to commons to avoid a direct dependency on the skip label name
- remove unnecessary assertions from hook error tests
- fix unescaped dots in metadata regular expressions

feat(allure-jasmine): selective run implementation

---

packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/test/spec/simple.test.ts

This changes provides fixes for #935, #792 where option `--reporter-allure-collection-as-parent-suite` did not work as expected.
- The options `--reporter-allure-collection-as-parent-suite` has been removed.
- Collection Container name will be as Parent Suite name by default.
- Test have been updated to reflect the new default nested structure.

fix(newman-reporter-allure): make Newman container name as parent suite name

---

packages/allure-js-commons/src/sdk/runtime/MessageTestRuntime.ts
packages/allure-js-commons/test/sdk/runtime/MessageTestRuntime.spec.ts

* Remove ANSI characters in the test steps (fixes #1076 )

fix: remove ansi characters in steps statusDetails

---

packages/allure-codeceptjs/src/reporter.ts
packages/allure-cucumberjs/src/reporter.ts
packages/allure-cypress/src/reporter.ts
packages/allure-jasmine/src/index.ts
packages/allure-jest/src/environmentFactory.ts
packages/allure-js-commons/src/sdk/reporter/utils.ts
packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-playwright/src/index.ts
packages/allure-vitest/src/reporter.ts
packages/newman-reporter-allure/src/index.ts

chore(allure-js-commons): add default writer factory

---

packages/allure-cypress/src/index.ts
packages/allure-cypress/src/model.ts
packages/allure-cypress/src/reporter.ts
packages/allure-cypress/src/runtime.ts
packages/allure-cypress/src/state.ts
packages/allure-cypress/src/utils.ts
packages/allure-cypress/test/spec/hooks.test.ts

If a hook fails, Mocha won't emit the `hook end` event. That caused the corresponding fixture to hang in the state until the process finishes instead of being written on disk.
Now, we're detecting those cases, and issuing the `cypress_hook_end` message in the Mocha's `fail` event if it corresponds to a hook error.
> [!NOTE]
> Spec-level after hooks are handled differently. See below.
In beta 10 we support spec-level `after` hooks by patching the `after` function to introduce two hooks instead of one. The first hook is the original user-defined one, while the second, the Allure-specific one, is responsible for flushing the messages of the original hook to Node.js.
That works just fine until the user-defined hook fails. In that case, Mocha skips its Allure-specific counterpart, which …

fix(allure-cypress): missing tests and fixtures when an error occurs in a hook

---

packages/allure-cucumberjs/src/reporter.ts
packages/allure-cucumberjs/test/samples/features/duration.feature
packages/allure-cucumberjs/test/samples/support/duration.cjs
packages/allure-cucumberjs/test/spec/duration.test.ts

fix(allure-cucumberjs): fix timings

---

packages/allure-jest/test/spec/hooks.test.ts
packages/allure-js-commons/src/sdk/reporter/LifecycleState.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/src/sdk/reporter/types.ts
packages/allure-js-commons/test/sdk/reporter/ReporterRuntime.spec.ts

feat(commons): process metadata messages from before hooks

---

packages/allure-cypress/README.md
packages/allure-cypress/src/model.ts
packages/allure-cypress/src/reporter.ts
packages/allure-cypress/src/runtime.ts
packages/allure-cypress/src/state.ts
packages/allure-cypress/src/utils.ts
packages/allure-cypress/test/spec/commands.test.ts
packages/allure-js-commons/src/sdk/index.ts
packages/allure-js-commons/src/sdk/reporter/utils.ts
packages/allure-js-commons/src/sdk/types.ts
packages/allure-js-commons/src/sdk/utils.ts
packages/allure-js-commons/test/sdk/reporter/utils.spec.ts
packages/allure-js-commons/test/sdk/utils.spec.ts
packages/allure-mocha/src/legacy.ts

Allure Cypress converts Cypress commands to Allure steps. Command argument values are converted to Allure step parameter values:
- strings are left unmodified,
- values of other types are converted with `JSON.stringify(value, null, 2)`.
The drawbacks:
- A `TypeError: Converting circular structure to JSON` is thrown if the value is an object with circular references. This is often the case when using Cypress commands with complex UI objects like Vue components, etc. See some examples in issue #1070.
- Complex objects and long strings/arrays can easily blow the report to ridiculous sizes
We have an existing function `serialize` defined in `allure-js-commons/sdk/reporter/utils`, which behaves similarly to what Allure Cypress does with Cypress step arguments. This PR:
1. Moves it to …

feat(allure-cypress): impose some limits on step parameter values created from Cypress command arguments

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/steps.spec.ts

fix(allure-playwright): ignore route.continue() steps

---

packages/allure-js-commons/src/sdk/utils.ts
packages/allure-js-commons/test/sdk/utils.spec.ts

fix(allure-js-commons): detect pw expect

---

packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-mocha/src/extraReporters.ts
packages/allure-mocha/src/types.ts
packages/allure-mocha/test/samples/customReporter.cjs
packages/allure-mocha/test/samples/reporter.cjs
packages/allure-mocha/test/samples/runner.js
packages/allure-mocha/test/spec/framework/extraReporters.test.ts
packages/allure-mocha/test/utils.ts

The PR makes it possible to enable additional reporters to run alongside Allure Mocha.
The feature is controlled by a new configuration property:`extraReporters`. Its values may take the following forms:
- A string: 
```js
{ extraReporters: "json" }
```
This is usable from the CLI or config files:
```shell
npx mocha -R allure-mocha -O extraReporters=json
```
*.mocharc.json:*
```json
{
"reporter": "allure-mocha",
"reporterOptions": [
"extraReporters=json"
],
}
```
- An array of one or two elements, where the second element (if present) is an options object:
```js
{ extraReporters: ["json", { output: "output.json" }] }
```
- An array of elements, each taking one of the above forms:
```js
{
extraReporters: [
["json", {output: "output.json"}],
"mochawesome",
],
}
```
Closes #1134.
[cla]: …

feat(mocha): add support for extra reporters

---

packages/allure-codeceptjs/src/index.ts
packages/allure-codeceptjs/test/spec/labels.test.ts
packages/allure-codeceptjs/test/spec/reporters.test.ts
packages/allure-codeceptjs/test/spec/testplan.test.ts
packages/allure-codeceptjs/test/utils.ts
packages/allure-codeceptjs/vitest.config.ts

CodeceptJS allows providing a reporter to an underlying instance of Mocha. Allure CodeceptJS itself is implemented as a reporter (based on Allure Mocha). It overwrites any configured reporter with itself, which prevents it from running alongside other reporters, including the default one, `cli`.
The incompatibility with `cli` manifests itself, particularly in the non-working `--steps`, `--debug`, and `--verbose` CLI options (see #1167).
#1182 allows extra reporters to run with the Allure Mocha reporter. This PR uses that functionality to enable the use of a user-provided reporter or a default one together with Allure CodeceptJS.
**caveat:** The implementation takes the configured reporter's constructor via the non-public `Mocha._reporter` field. It's quite stable, though (the field hasn't …

feat(codeceptjs): add support for mocha reporters

---

packages/allure-codeceptjs/package.json
packages/allure-cucumberjs/package.json
packages/allure-cypress/package.json
packages/allure-jasmine/package.json
packages/allure-jest/package.json
packages/allure-js-commons/package.json
packages/allure-mocha/package.json
packages/allure-playwright/package.json
packages/allure-vitest/package.json

When resolving types, TypeScript always uses the "types" entry of "exports" (provided it exists) regardless of its position and whether or not a previous entry had matched.
This is considered a bug and shouldn't be relied upon. See the details here: microsoft/TypeScript#50762.
This PR puts every "types" entry to the first place. This makes the resolution by TypeScript the same as the one performed by Node.

fix: invalid position of "types" in "exports"

---

.eslintrc.cjs
.prettierrc.js
packages/allure-codeceptjs/test/utils.ts
packages/allure-jasmine/test/utils.ts
packages/allure-mocha/src/extraReporters.ts
packages/allure-mocha/test/spec/framework/fixtures.test.ts
packages/allure-mocha/test/spec/framework/retries.test.ts
packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/test/spec/errorMessage.test.ts
packages/newman-reporter-allure/test/spec/exec.test.ts
packages/newman-reporter-allure/test/spec/globalLabels.test.ts
packages/newman-reporter-allure/test/spec/headers.test.ts
packages/newman-reporter-allure/test/spec/requestError.test.ts
packages/newman-reporter-allure/test/spec/simple.test.ts
packages/newman-reporter-allure/test/spec/syntaxError.test.ts

- Set `quoteProps` to `"consistent"` to match ESLint's `quote-props` rule.
- Set `avoidEscape` to `true` for ESLint's `@stylistic/quotes` rule to match Prettier's formatting behavior when dealing with strings with double quote characters inside (e.g., `'"foo"="bar"'`).
ref https://github.com/allure-framework/allure3/pull/29

chore: improve interop between prettier and eslint

---

packages/allure-codeceptjs/src/reporter.ts
packages/allure-codeceptjs/test/spec/assert.test.ts
packages/allure-js-commons/src/sdk/utils.ts

CodeceptJS has an internal AssertionFailedError. The proposed change adds
support for it.
fixes #1195 

fix(codeceptjs): add support for native asserts

---

packages/allure-js-commons/src/model.ts
packages/allure-js-commons/src/sdk/utils.ts
packages/allure-js-commons/test/sdk/utils.spec.ts
packages/allure-vitest/test/spec/expect.test.ts

New model fields: `statusDetails.actual` and `statusDetails.expected`
that can be used to provide `actual` and `expected` values for errors.
Actual and expected values automatically processed  when `getMessageAndTraceFromError` method is used to get 
message and trace from error (almost all the integrations)

Add support for actual and expected values in errors

---

packages/allure-cucumberjs/test/spec/globalLabels.test.ts
packages/allure-cypress/test/spec/globalLabels.test.ts
packages/allure-jasmine/test/spec/globalLabels.test.ts
packages/allure-jest/test/spec/globalLabels.test.ts
packages/allure-js-commons/src/sdk/reporter/ReporterRuntime.ts
packages/allure-js-commons/src/sdk/reporter/types.ts
packages/allure-mocha/test/spec/framework/globalLabels.test.ts
packages/allure-mocha/test/utils.ts
packages/allure-playwright/test/spec/globalLabels.test.ts
packages/allure-vitest/test/spec/globalLabels.test.ts

Previously it was possible to use array of `Label` type to configure global labels. Now users can define them by `Record<string, string | string[]>` as well.

Enchance global labels definition

---

packages/allure-js-commons/src/sdk/utils.ts
packages/allure-js-commons/test/sdk/utils.spec.ts

Support spaces in the title metadata format

---

packages/allure-cypress/src/browser/commandLog.ts
packages/allure-cypress/src/browser/events/cypress.ts
packages/allure-cypress/src/browser/state.ts
packages/allure-cypress/src/browser/utils.ts
packages/allure-cypress/test/spec/security.test.ts

Fix cypress issues

---

packages/allure-js-commons/src/sdk/index.ts
packages/allure-js-commons/src/sdk/utils.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/annotations.spec.ts
packages/allure-playwright/test/spec/runtime/legacy/tags.spec.ts
packages/allure-playwright/test/spec/runtime/modern/tags.spec.ts
packages/allure-playwright/vitest.config.ts

The PR is a just continuation of #1220.
After a short discussion with @baev, we decided to divide Playwright annotations on 3 different types:
- well-known annotations such as `fixme`, `issue`, `skip` etc., which should be processed in a certain way
- Allure Metadata annotations which starts with `@allure.` or `allure.` prefix (e.g. `@allure.id` or `allure.label.epic`) which appears in the labels
- rest annotations which should be presented as empty steps with name matching `annotation name: annotation description` pattern

Support allure metadata in playwright test and group annotations v2.0

---

packages/allure-codeceptjs/test/spec/titleMetadata.test.ts
packages/allure-cypress/src/browser/testplan.ts
packages/allure-cypress/src/browser/utils.ts
packages/allure-cypress/test/spec/runtime/legacy/titleMetadata.test.ts
packages/allure-cypress/test/spec/runtime/modern/titleMetadata.test.ts
packages/allure-jasmine/src/index.ts
packages/allure-jasmine/src/utils.ts
packages/allure-jasmine/test/spec/metadata.test.ts
packages/allure-jest/src/environmentFactory.ts
packages/allure-jest/test/spec/metadata.test.ts
packages/allure-js-commons/src/sdk/utils.ts
packages/allure-js-commons/test/sdk/utils.spec.ts
packages/allure-mocha/src/AllureMochaReporter.ts
packages/allure-mocha/src/types.ts
packages/allure-mocha/src/utils.ts
packages/allure-mocha/test/samples/spec/links/meta/multiple.spec.js
packages/allure-mocha/test/samples/spec/links/meta/single.spec.js
packages/allure-mocha/test/spec/api/metadata.test.ts
packages/allure-mocha/test/utils.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/test/spec/titleMetadata.spec.ts
packages/allure-vitest/src/reporter.ts
packages/allure-vitest/src/utils.ts
packages/allure-vitest/test/spec/titleMetadata.test.ts
packages/newman-reporter-allure/src/index.ts
packages/newman-reporter-allure/src/utils.ts
packages/newman-reporter-allure/test/spec/simple.test.ts

Support links in allure string metadata format

---

packages/allure-codeceptjs/src/model.ts
packages/allure-codeceptjs/src/reporter.ts
packages/allure-codeceptjs/test/spec/pageObject.test.ts

feat(codeceptjs): add support for meta steps

---

packages/allure-playwright/src/index.ts
packages/allure-playwright/src/runtime.ts
packages/allure-playwright/test/spec/runtime/legacy/steps.spec.ts
packages/allure-playwright/test/spec/runtime/modern/steps.spec.ts

Fix step context metadata for Playwright

---

packages/allure-js-commons/src/facade.ts
packages/allure-js-commons/src/index.ts
packages/allure-js-commons/src/sdk/reporter/utils/extensions.ts
packages/allure-js-commons/test/sdk/reporter/utils/attachments.spec.ts
packages/allure-playwright/src/index.ts
packages/allure-playwright/src/runtime.ts
packages/allure-playwright/test/spec/attachments.spec.ts

Add special contentType `application/playwright-trace` for Playwright Trace archives.

feat: add function to attach Playwright Trace

---

packages/allure-mocha/test/spec/framework/extraReporters.test.ts
packages/allure-mocha/test/utils.ts

When capturing stdout/stderr, the Mocha test runner treats chunks as lines. While in most cases it's true, sometimes chunks aren't aligned with lines, which fail the tests that depend on the correct line splitting (e.g., a test that checks multiple extra reporters that both write to stdout).
The PR ensures the Mocha test runner correctly combines stdout/stderr chunks into single strings. It's up to tests to decide how to treat such strings and how to split them into separate lines if necessary.

test(mocha): fix unstable tests that depend on stdout/stderr line splitting
